version: '3.8'

services:
  app:
    image: devops-demo-app:staging
    container_name: demo-app-staging
    ports:
      - "5001:5000"
    environment:
      - APP_VERSION=1.0.0
      - APP_ENV=staging
      - PORT=5000
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    restart: always

  redis:
    container_name: demo-redis-staging
    ports:
      - "6380:6379"
